### ISSUE TITLE
MultiTenantApplication not working

### ISSUE THREAD

**Issue by grahamehorner** [OrchardCMS/OrchardCore.Samples#4] opened 2017-10-25 09:59 UTC
The MultiTenantApplication is throwing an expection on startup; and not responding to browser requests

Hosting environment: Development
Content root path: C:\Users\local.user\source\repos\orchard-core-samples\MultiTenantApplication
Now listening on: http://localhost:55207
Application started. Press Ctrl+C to shut down.
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[11]
      Hosting startup assembly exception
System.InvalidOperationException: Startup assembly Microsoft.AspNetCore.ApplicationInsights.HostingStartup failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.ApplicationInsights.HostingStartup, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   --- End of inner exception stack trace ---
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:55207/
info: OrchardCore.Environment.Shell.ShellHost[0]
      Start creation of shells
info: OrchardCore.Environment.Extensions.Loaders.AmbientExtensionLoader[0]
      Loaded referenced ambient extension "Module1": assembly name="Module1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
info: OrchardCore.Environment.Extensions.Loaders.AmbientExtensionLoader[0]
      Loaded referenced ambient extension "Module2": assembly name="Module2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
info: OrchardCore.Environment.Extensions.Loaders.AmbientExtensionLoader[0]
      Loaded referenced ambient extension "OrchardCore.Mvc": assembly name="OrchardCore.Mvc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
info: OrchardCore.Environment.Shell.Builders.ShellContextFactory[0]
      Creating shell context for tenant Acme
info: OrchardCore.Environment.Shell.Builders.ShellContextFactory[0]
      Creating shell context for tenant Contoso
fail: OrchardCore.Environment.Shell.ShellHost[0]
      A tenant could not be started: Contoso
System.AggregateException: One or more errors occurred. (Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.) ---> System.InvalidOperationException: Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at OrchardCore.Environment.Shell.Builders.ServiceProviderExtensions.CreateChildContainer(IServiceProvider serviceProvider, IServiceCollection serviceCollection)
   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.<CreateDescribedContextAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.<OrchardCore-Environment-Shell-Builders-IShellContextFactory-CreateShellContextAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at OrchardCore.Environment.Shell.ShellHost.<>c__DisplayClass11_0.<GetOrCreateShellContext>b__0(String tenant)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at OrchardCore.Environment.Shell.ShellHost.<CreateAndRegisterShellsAsync>b__13_0(ShellSettings settings)
---> (Inner Exception #0) System.InvalidOperationException: Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at OrchardCore.Environment.Shell.Builders.ServiceProviderExtensions.CreateChildContainer(IServiceProvider serviceProvider, IServiceCollection serviceCollection)
   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.<CreateDescribedContextAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.<OrchardCore-Environment-Shell-Builders-IShellContextFactory-CreateShellContextAsync>d__5.MoveNext()<---

fail: OrchardCore.Environment.Shell.ShellHost[0]
      A tenant could not be started: Acme
System.AggregateException: One or more errors occurred. (Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.) ---> System.InvalidOperationException: Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at OrchardCore.Environment.Shell.Builders.ServiceProviderExtensions.CreateChildContainer(IServiceProvider serviceProvider, IServiceCollection serviceCollection)
   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.<CreateDescribedContextAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.<OrchardCore-Environment-Shell-Builders-IShellContextFactory-CreateShellContextAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at OrchardCore.Environment.Shell.ShellHost.<>c__DisplayClass11_0.<GetOrCreateShellContext>b__0(String tenant)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at OrchardCore.Environment.Shell.ShellHost.<CreateAndRegisterShellsAsync>b__13_0(ShellSettings settings)
---> (Inner Exception #0) System.InvalidOperationException: Unable to resolve service for type 'System.Text.Encodings.Web.JavaScriptEncoder' while attempting to activate 'Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, ISet`1 callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at OrchardCore.Environment.Shell.Builders.ServiceProviderExtensions.CreateChildContainer(IServiceProvider serviceProvider, IServiceCollection serviceCollection)
   at OrchardCore.Environment.Shell.Builders.ShellContainerFactory.CreateContainer(ShellSettings settings, ShellBlueprint blueprint)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.<CreateDescribedContextAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Environment.Shell.Builders.ShellContextFactory.<OrchardCore-Environment-Shell-Builders-IShellContextFactory-CreateShellContextAsync>d__5.MoveNext()<---

info: OrchardCore.Environment.Shell.ShellHost[0]
      Done creating shells
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 450.1979ms 200

**Comment by sebastienros** [comment] 2017-10-25 17:22
Please add `services.AddSingleton(JavaScriptEncoder.Default);` in the main startup

**Comment by sebastienros** [comment] 2017-10-25 17:23
see https://github.com/OrchardCMS/OrchardCore.Samples/issues/5

**Comment by sebastienros** [comment] 2018-02-16 17:58
Duplicate of #5

**Closed by sebastienros** 2018-02-16 17:58 UTC
